name: 'Merge OpenAPI Specs'
description: 'Merge multiple OpenAPI specification files into a single YAML file'
author: 'Stainless Team <support@stainless.com>'

inputs:
  input_files:
    description: 'Glob patterns or file paths of OpenAPI spec files to merge (e.g., "services/**/*.yaml" or "api1.json,api2.yaml")'
    required: true
  output_path:
    description: 'Path where the merged file will be saved'
    required: false
    default: './merged-openapi.yaml'

outputs:
  merged_file:
    description: 'Path to the merged OpenAPI specification file'
  path_count:
    description: 'Total number of paths in the merged specification'

runs:
  using: 'node20'
  main: 'dist/index.js'

branding:
  icon: 'layers'
  color: 'blue'