name: 'Merge OpenAPI Specs'
description: 'Merge multiple OpenAPI specification files into a single YAML file'
author: 'Stainless Team <support@stainless.com>'

inputs:
  input_files:
    description: 'Glob patterns or file paths of OpenAPI spec files to merge (e.g., "services/**/*.yaml" or "api1.json,api2.yaml")'
    required: true
  output_path:
    description: 'Path where the merged file will be saved'
    required: false
    default: './merged-openapi.yaml'

outputs:
  merged_file:
    description: 'Path to the merged OpenAPI specification file'
    value: ${{ steps.merge.outputs.merged_file }}
  path_count:
    description: 'Total number of paths in the merged specification'
    value: ${{ steps.merge.outputs.path_count }}

runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install dependencies
      shell: bash
      run: |
        npm install -g @redocly/cli
        sudo apt-get update
        sudo apt-get install -y jq
        # Install yq
        sudo wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
        sudo chmod +x /usr/local/bin/yq

    - name: Merge OpenAPI specs
      id: merge
      shell: bash
      run: |
        bash ${{ github.action_path }}/merge-specs.sh "${{ inputs.input_files }}" "${{ inputs.output_path }}"

branding:
  icon: 'layers'
  color: 'blue'