openapi: 3.0.0
info:
  title: Conflict Test 2
  version: 1.0.0
paths:
  /users:
    get:
      summary: Get users from service 2
      responses:
        '200':
          description: Success
  /products:
    get:
      summary: Get products
      responses:
        '200':
          description: Success